// <auto-generated />
using System;
using GridSync.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GridSync.Api.Persistence.Migrations
{
    [DbContext(typeof(GridSyncDbContext))]
    partial class GridSyncDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GridSync.Api.Persistence.OpLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Col")
                        .HasColumnType("int");

                    b.Property<int>("Counter")
                        .HasColumnType("int");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Row")
                        .HasColumnType("int");

                    b.Property<string>("SheetId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Value")
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("WallMs")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SheetId", "Id");

                    b.ToTable("OpLog");
                });

            modelBuilder.Entity("GridSync.Api.Persistence.SheetSnapshot", b =>
                {
                    b.Property<string>("SheetId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CellsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UpToOpId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("WrittenAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("SheetId");

                    b.ToTable("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
